=== labsquid/Lab07/data/template.dtd
<!ELEMENT timetable ((day|timeslot|course)+)>

<!ELEMENT booking (type,room,((day, course)|(day, timeslot)|(course, timeslot)),teacher)>

<!ELEMENT type EMPTY>
<!ATTLIST type
    type (Lab|Lecture) #REQUIRED
>

<!ELEMENT teacher EMPTY>
<!ATTLIST teacher
    teacher CDATA #REQUIRED
>

<!ELEMENT room EMPTY>
<!ATTLIST room
    room CDATA #REQUIRED
>

<!ELEMENT day (booking*)>
<!ATTLIST day
    day (Monday | Tuesday | Wednesday | Thursday | Friday) #REQUIRED
>

<!ELEMENT course (booking*)>
<!ATTLIST course
    course CDATA #REQUIRED
>

<!ELEMENT timeslot (booking*)>
<!ATTLIST timeslot
    time CDATA #REQUIRED
>

=== labsquid/Lab07/data-day.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE timetable SYSTEM "template.dtd">
<timetable>
	<day day='Monday'>
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
			<course course="ACIT4770"/>
			<timeslot time="13:30"/>
		</booking>
		
		<booking>
			<type type="Lecture"/>
			<room room="SW9-206"/>
			<course course="ACIT4910"/>
			<timeslot time="13:30"/>
		</booking>
		
		<booking>
			<type type="Lecture"/>
			<room room="SE6-205"/>
			<course course="ACIT4650"/>
			<timeslot time="16:30"/>
		</booking>
	</day>
	
	<day day='Tuesday'>
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
			<course course="ACIT4620"/>
			<timeslot time="10:30"/>
		</booking>
		
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
			<course course="ACIT4620"/>
			<timeslot time="11:30"/>
		</booking>
		
		<booking>
			<type type="Lecture"/>
			<room room="SW9-206"/>
			<course course="ACIT4650"/>
			<timeslot time="12:30"/>
		</booking>
		
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
			<course course="ACIT4650"/>
			<timeslot time="13:30"/>
		</booking>
		
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
			<course course="ACIT4650"/>
			<timeslot time="14:30"/>
		</booking>
		
		<booking>
			<type type="Lecture"/>
			<room room="SW3-3615"/>
			<course course="ACIT4620"/>
			<timeslot time="15:30"/>
		</booking>
	</day>
	<day day='Wednesday'>
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
			<course course="ACIT4660"/>
			<timeslot time="10:30"/>
		</booking>
		
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
			<course course="ACIT4660"/>
			<timeslot time="11:30"/>
		</booking>
		
		<booking>
			<type type="Lecture"/>
			<room room="SW3-1750"/>
			<course course="ACIT4850"/>
			<timeslot time="12:30"/>
		</booking>
		<booking>
			<type type="Lecture"/>
			<room room="SW3-1750"/>
			<course course="ACIT4850"/>
			<timeslot time="13:30"/>
		</booking>
	</day>
	<day day='Thursday'>
		<booking>
			<type type="Lecture"/>
			<room room="SW5-1840"/>
			<course course="ACIT4910"/>
			<timeslot time="9:30"/>
		</booking>
		
		<booking>
			<type type="Lab"/>
			<room room="SE12-320"/>
			<course course="ACIT4850"/>
			<timeslot time="10:30"/>
		</booking>
		
		<booking>
			<type type="Lab"/>
			<room room="SE12-320"/>
			<course course="ACIT4850"/>
			<timeslot time="11:30"/>
		</booking>
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
			<course course="ACIT4910"/>
			<timeslot time="13:30"/>
		</booking>
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
			<course course="ACIT4910"/>
			<timeslot time="14:30"/>
		</booking>
	</day>
	<day day='Friday'>
		<booking>
			<type type="Lecture"/>
			<room room="SW9-206"/>
			<course course="ACIT4660"/>
			<timeslot time="8:30"/>
		</booking>
		<booking>
			<type type="Lecture"/>
			<room room="SW9-206"/>
			<course course="ACIT4660"/>
			<timeslot time="9:30"/>
		</booking>
		<booking>
			<type type="Lecture"/>
			<room room="SW9-206"/>
			<course course="ACIT4660"/>
			<timeslot time="10:30"/>
		</booking>
	</day>
</timetable>

=== labsquid/Lab07/test-data.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE timetable SYSTEM "template.dtd">
<timetable>
	<day day='Monday'>
		<booking>
			<type type="Lab"/>
			<room room="3060"/>
                        <day day='Monday'/>
                        <course course="ACIT4650"/>
			<timeslot time="10:30"/>
		</booking>
	</day>

	<timeslot time='ACIT4650'>
		<booking>
			<type type="Lab"/>
			<room room="3060"/>
                        <day day="Tuesday"/>
			<course course="ACIT4650"/>	
		</booking>
	</timeslot>

	<course course='ACIT4650'>
		<booking>
			<type type="Lab"/>
			<room room="3060"/>
                        <day day="Tuesday"/>
			<timeslot time="10:30"/>
		</booking>
	</course>

</timetable>

=== labsquid/Lab07/data/data-course.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE timetable SYSTEM "template.dtd">
<timetable>
	<course course="ACIT4910">
		<booking>
			<type type="Lecture"/>
			<room room="SW5-1840"/>
			<day day='Monday'/>
			<timeslot time="13:30"/>
			<teacher teacher="Richard Chau"/>
		</booking>
		<booking>
			<type type="Lecture"/>
			<room room="SW5-1840"/>
			<day day='Thursday'/>
			<timeslot time="9:30"/>
			<teacher teacher="Richard Chau"/>
		</booking>
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
			<day day='Thursday'/>
			<timeslot time="13:30"/>
			<teacher teacher="Richard Chau"/>
		</booking>
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
			<day day='Thursday'/>
			<timeslot time="14:30"/>
			<teacher teacher="Richard Chau"/>
		</booking>
	</course>
        
	<course course = "ACIT4770">
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
			<day day='Monday'/>
			<timeslot time="13:30"/>
			<teacher teacher="Trevor Lord"/>
		</booking>
	</course>
	<course course = "ACIT4650">
		<booking>
			<type type="Lecture"/>
			<room room="SE6-205"/>
			<day day='Monday'/>
			<timeslot time="16:30"/>
			<teacher teacher="Medhat Elmasry"/>
		</booking>
		<booking>
			<type type="Lecture"/>
			<room room="SE6-205"/>
			<day day = 'Tuesday'/>
			<timeslot time="16:30"/>
			<teacher teacher="Medhat Elmasry"/>
		</booking>
        <booking>
			<type type="Lecture"/>
			<room room="SW9-206"/>
			<day day = 'Tuesday'/>
			<timeslot time="12:30"/>
			<teacher teacher="Medhat Elmasry"/>
		</booking>
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
			<day day = 'Tuesday'/>
			<timeslot time="14:30"/>
			<teacher teacher="Medhat Elmasry"/>
		</booking>		
	</course>
	<course course = "ACIT4620">
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
			<day day = 'Tuesday'/>
			<timeslot time="10:30"/>
			<teacher teacher="Bethany Edmunds"/>
		</booking>
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
			<day day = 'Tuesday'/>
			<timeslot time="11:30"/>
			<teacher teacher="Bethany Edmunds"/>
		</booking>
		<booking>
			<type type="Lecture"/>
			<room room="SW3-3615"/>
			<day day = 'Tuesday'/>
			<timeslot time="15:30"/>
			<teacher teacher="Bethany Edmunds"/>
		</booking>
	</course>
	<course course="ACIT4660">
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
			<day day = 'Wednesday'/>
			<timeslot time="10:30"/>
			<teacher teacher="Stephen Fabiszewski"/>
		</booking>
		
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
			<day day = 'Wednesday'/>
			<timeslot time="11:30"/>
			<teacher teacher="Stephen Fabiszewski"/>
		</booking>
		<booking>
			<type type="Lecture"/>
			<room room="SW9-206"/>
			<day day = 'Friday'/>
			<timeslot time="8:30"/>
			<teacher teacher="Stephen Fabiszewski"/>
		</booking>
		<booking>
			<type type="Lecture"/>
			<room room="SW9-206"/>
			<day day = 'Friday'/>
			<timeslot time="9:30"/>
			<teacher teacher="Stephen Fabiszewski"/>
		</booking>
		<booking>
			<type type="Lecture"/>
			<room room="SW9-206"/>
			<day day = 'Friday'/>
			<timeslot time="10:30"/>
			<teacher teacher="Stephen Fabiszewski"/>
		</booking>
	</course>
	<course course="ACIT4850">
		<booking>
			<type type="Lecture"/>
			<room room="SW3-1750"/>
			<day day = 'Wednesday'/>
			<timeslot time="12:30"/>
			<teacher teacher="James Parry"/>
		</booking>
		<booking>
			<type type="Lecture"/>
			<room room="SW3-1750"/>
			<day day = 'Wednesday'/>
			<timeslot time="13:30"/>
			<teacher teacher="James Parry"/>
		</booking>
		<booking>
			<type type="Lab"/>
			<room room="SE12-320"/>
			<day day = 'Thursday'/>
			<timeslot time="10:30"/>
			<teacher teacher="James Parry"/>
		</booking>	
		<booking>
			<type type="Lab"/>
			<room room="SE12-320"/>
			<day day = 'Thursday'/>
			<timeslot time="11:30"/>
			<teacher teacher="James Parry"/>
		</booking>
	</course>
</timetable>

=== labsquid/Lab07/data-timeslot.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE timetable SYSTEM "template.dtd">
<timetable>
	<timeslot time="8:30">
		<booking>
			<type type="Lecture"/>
			<room room="SW9-206"/>
			<course course="ACIT4660"/>
		</booking>
	</timeslot>
	<timeslot time="9:30">
		<booking>
			<type type="Lecture"/>
			<room room="SW5-1840"/>
			<course course="ACIT4910"/>
		</booking>
		<booking>
			<type type="Lecture"/>
			<room room="SW9-206"/>
			<course course="ACIT4660"/>
		</booking>
	</timeslot>
	<timeslot time="10:30">
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
			<course course="ACIT4620"/>
		</booking>
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
			<course course="ACIT4660"/>
		</booking>
		<booking>
			<type type="Lecture"/>
			<room room="SW9-206"/>
			<course course="ACIT4660"/>
		</booking>
		<booking>
			<type type="Lab"/>
			<room room="SE12-320"/>
			<course course="ACIT4850"/>
		</booking>
	</timeslot>
	<timeslot time="11:30">
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
			<course course="ACIT4620"/>
		</booking>
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
			<course course="ACIT4660"/>
		</booking>
		<booking>
			<type type="Lab"/>
			<room room="SE12-320"/>
			<course course="ACIT4850"/>
		</booking>
	</timeslot>
	<timeslot time="12:30">
		<booking>
			<type type="Lecture"/>
			<room room="SW9-206"/>
			<course course="ACIT4650"/>
		</booking>
		<booking>
			<type type="Lecture"/>
			<room room="SW3-1750"/>
			<course course="ACIT4850"/>
		</booking>
	</timeslot>
	<timeslot time="13:30">
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
			<course course="ACIT4770"/>
		</booking>
		<booking>
			<type type="Lecture"/>
			<room room="SW9-206"/>
			<course course="ACIT4910"/>
		</booking>
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
			<course course="ACIT4650"/>
		</booking>
		<booking>
			<type type="Lecture"/>
			<room room="SW3-1750"/>
			<course course="ACIT4850"/>
		</booking>
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
			<course course="ACIT4910"/>
		</booking>
	</timeslot>
	<timeslot time="14:30">
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
			<course course="ACIT4650"/>
		</booking>
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
			<course course="ACIT4910"/>
		</booking>
	</timeslot>
	<timeslot time="15:30">
		<booking>
			<type type="Lecture"/>
			<room room="SW3-3615"/>
			<course course="ACIT4620"/>
		</booking>		
	</timeslot>
	<timeslot time="16:30">
		<booking>
			<type type="Lecture"/>
			<room room="SE6-205"/>
			<course course="ACIT4650"/>
		</booking>
	</timeslot>
	<timeslot time="17:30">
	</timeslot>
</timetable>

=== labsquid/Lab07/data/data-timeslot.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE timetable SYSTEM "template.dtd">
<timetable>
	<timeslot time="8:30">
		<booking>
			<type type="Lecture"/>
			<room room="SW9-206"/>
                        <day day="Friday"/>
			<course course="ACIT4660"/>
			<teacher teacher="Stephen Fabiszewski"/>
		</booking>
	</timeslot>
	<timeslot time="9:30">
		<booking>
			<type type="Lecture"/>
			<room room="SW5-1840"/>
			<day day="Thursday"/>
                        <course course="ACIT4910"/>
			<teacher teacher="Richard Chau"/>
		</booking>
		<booking>
			<type type="Lecture"/>
			<room room="SW9-206"/>
            <day day="Friday"/>
			<course course="ACIT4660"/>
			<teacher teacher="Stephen Fabiszewski"/>
		</booking>
	</timeslot>
	<timeslot time="10:30">
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
            <day day="Tuesday"/>
			<course course="ACIT4620"/>
			<teacher teacher="Bethany Edmunds"/>
		</booking>
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
            <day day="Wednesday"/>
			<course course="ACIT4660"/>
			<teacher teacher="Stephen Fabiszewski"/>
		</booking>
		<booking>
			<type type="Lecture"/>
			<room room="SW9-206"/>
            <day day="Friday"/>
			<course course="ACIT4660"/>
			<teacher teacher="Stephen Fabiszewski"/>
		</booking>
		<booking>
			<type type="Lab"/>
			<room room="SE12-320"/>
            <day day="Thursday"/>
			<course course="ACIT4850"/>
			<teacher teacher="James Parry"/>
		</booking>
	</timeslot>
	<timeslot time="11:30">
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
            <day day="Tuesday"/>
			<course course="ACIT4620"/>
			<teacher teacher="Bethany Edmunds"/>
		</booking>
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
            <day day="Wednesday"/>
			<course course="ACIT4660"/>
			<teacher teacher="Stephen Fabiszewski"/>
		</booking>
		<booking>
			<type type="Lab"/>
			<room room="SE12-320"/>
            <day day="Thursday"/>
			<course course="ACIT4850"/>
			<teacher teacher="James Parry"/>
		</booking>
	</timeslot>
	<timeslot time="12:30">
		<booking>
			<type type="Lecture"/>
			<room room="SW9-206"/>
            <day day="Tuesday"/>
			<course course="ACIT4650"/>
			<teacher teacher="Medhat Elmasry"/>
		</booking>
		<booking>
			<type type="Lecture"/>
			<room room="SW3-1750"/>
            <day day="Wednesday"/>
			<course course="ACIT4850"/>
			<teacher teacher="James Parry"/>
		</booking>
	</timeslot>
	<timeslot time="13:30">
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
            <day day="Monday"/>
			<course course="ACIT4770"/>
			<teacher teacher="Trevor Lord"/>
		</booking>
		
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
            <day day="Tuesday"/>
			<course course="ACIT4650"/>
			<teacher teacher="Medhat Elmasry"/>
		</booking>
		<booking>
			<type type="Lecture"/>
			<room room="SW3-1750"/>
            <day day="Wednesday"/>
			<course course="ACIT4850"/>
			<teacher teacher="James Parry"/>
		</booking>
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
            <day day="Thursday"/>
			<course course="ACIT4910"/>
			<teacher teacher="Richard Chau"/>
		</booking>
	</timeslot>
	<timeslot time="14:30">
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
            <day day="Tuesday"/>
			<course course="ACIT4650"/>
			<teacher teacher="Medhat Elmasry"/>
		</booking>
		<booking>
			<type type="Lab"/>
			<room room="SE12-306"/>
            <day day="Thursday"/>
			<course course="ACIT4910"/>
			<teacher teacher="Richard Chau"/>
		</booking>
	</timeslot>
	<timeslot time="15:30">
		<booking>
			<type type="Lecture"/>
			<room room="SW3-3615"/>
            <day day="Tuesday"/>
			<course course="ACIT4620"/>
			<teacher teacher="Bethany Edmunds"/>
		</booking>		
                <booking>
			<type type="Lecture"/>
			<room room="SW9-206"/>
            <day day="Monday"/>
			<course course="ACIT4910"/>
			<teacher teacher="Richard Chau"/>
		</booking>
	</timeslot>
	<timeslot time="16:30">
		<booking>
			<type type="Lecture"/>
			<room room="SE6-205"/>
            <day day="Monday"/>
			<course course="ACIT4650"/>
			<teacher teacher="Medhat Elmasry"/>
		</booking>
	</timeslot>
	<timeslot time="17:30">
	</timeslot>
</timetable>
